[package]
name = "munge"
version = "0.2.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2021"
description = "Macro for easily initializing `MaybeUninit`s"
license = "MIT"
documentation = "https://docs.rs/munge"
repository = "https://github.com/djkoloski/munge"
keywords = ["munge", "macro", "initialize"]
categories = ["no-std", "rust-patterns"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
compiletest_rs = "0.7"

[features]
default = []
offset_of = []
